sudo: required
services:
    - docker

before_install:
    - docker build -t zhengleiwei/docker-react -f Dockerfile.dev .
    
script:
    - docker run zhengleiwei/docker-react npm run test -- --coverage

